pub struct HtmlReport;

impl HtmlReport {
    pub fn generate_header(title: &str) -> String {
        format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; background: #1a1a1a; color: #fff; }}
        h1 {{ color: #00ff88; }}
        h2 {{ color: #00ccff; }}
        table {{ border-collapse: collapse; width: 100%; margin-top: 20px; }}
        th {{ background: #333; color: #00ff88; padding: 10px; text-align: left; }}
        td {{ padding: 8px; border-bottom: 1px solid #444; }}
        .critical {{ color: #ff4444; font-weight: bold; }}
        .high {{ color: #ff8800; }}
        .medium {{ color: #ffcc00; }}
        .low {{ color: #88ff88; }}
        .info {{ color: #8888ff; }}
        .finding:hover {{ background: #2a2a2a; }}
    </style>
</head>
<body>
    <h1>{}</h1>
"#,
            title, title
        )
    }

    pub fn generate_footer() -> String {
        r#"
    <footer style="margin-top: 40px; text-align: center; color: #666;">
        <p>Generated by OXIDE - Open eXtensible Intelligence & Detection Engine</p>
    </footer>
</body>
</html>"#
        .to_string()
    }

    pub fn generate_table_start() -> String {
        r#"<table>
    <thead>
        <tr>
            <th>Severity</th>
            <th>URL</th>
            <th>Title</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>"#
        .to_string()
    }

    pub fn generate_table_end() -> String {
        "</tbody></table>".to_string()
    }
}
