pub struct PayloadGenerator;

impl PayloadGenerator {
    pub fn new() -> Self {
        Self
    }

    pub fn generate_paths(&self) -> Vec<String> {
        vec![
            "/".to_string(),
            "/admin".to_string(),
            "/login".to_string(),
            "/api".to_string(),
            "/config".to_string(),
            "/.env".to_string(),
            "/robots.txt".to_string(),
            "/sitemap.xml".to_string(),
            "/.git/".to_string(),
            "/.svn/".to_string(),
            "/backup/".to_string(),
            "/phpinfo.php".to_string(),
            "/admin.php".to_string(),
            "/wp-admin/".to_string(),
            "/wp-login.php".to_string(),
            "/administrator/".to_string(),
            "/admin/login".to_string(),
            "/admin/dashboard".to_string(),
            "/api/v1/users".to_string(),
            "/api/v1/admin".to_string(),
            "/swagger.json".to_string(),
            "/api-docs/".to_string(),
            "/graphql".to_string(),
            "/actuator/health".to_string(),
            "/actuator/info".to_string(),
            "/debug".to_string(),
            "/test".to_string(),
            "/dev".to_string(),
            "/staging".to_string(),
            "/prod".to_string(),
            "/console".to_string(),
            "/shell".to_string(),
            "/status".to_string(),
            "/metrics".to_string(),
            "/health".to_string(),
            "/ping".to_string(),
            "/trace".to_string(),
            "/dump".to_string(),
            "/logs/".to_string(),
            "/tmp/".to_string(),
            "/temp/".to_string(),
            "/uploads/".to_string(),
            "/files/".to_string(),
            "/data/".to_string(),
            "/db/".to_string(),
            "/database/".to_string(),
            "/sql/".to_string(),
            "/backup.sql".to_string(),
            "/dump.sql".to_string(),
            "/database.sql".to_string(),
            "/db.sql".to_string(),
            "/.htaccess".to_string(),
            "/.htpasswd".to_string(),
            "/web.config".to_string(),
            "/crossdomain.xml".to_string(),
            "/clientaccesspolicy.xml".to_string(),
            "/.well-known/security.txt".to_string(),
            "/server-status".to_string(),
            "/server-info".to_string(),
            "/jmx-console/".to_string(),
            "/manager/html".to_string(),
            "/host-manager/html".to_string(),
            "/invoker/JMXInvokerServlet".to_string(),
            "/cgi-bin/".to_string(),
            "/bin/".to_string(),
            "/cgi/".to_string(),
            "/scripts/".to_string(),
            "/fcgi-bin/".to_string(),
            "/phpMyAdmin/".to_string(),
            "/pma/".to_string(),
            "/myadmin/".to_string(),
            "/mysql/".to_string(),
            "/sqlmanager/".to_string(),
            "/.docker/".to_string(),
            "/docker-compose.yml".to_string(),
            "/Dockerfile".to_string(),
            "/.kubernetes/".to_string(),
            "/.k8s/".to_string(),
            "/jenkins/".to_string(),
            "/gitlab/".to_string(),
            "/grafana/".to_string(),
            "/prometheus/".to_string(),
            "/kibana/".to_string(),
            "/elasticsearch/".to_string(),
            "/rabbitmq/".to_string(),
            "/redis/".to_string(),
            "/mongo-express/".to_string(),
            "/swagger-ui.html".to_string(),
            "/api/swagger-ui.html".to_string(),
            "/v2/api-docs".to_string(),
            "/api/v2/api-docs".to_string(),
            "/openapi.json".to_string(),
            "/api/openapi.json".to_string(),
        ]
    }

    pub fn generate_params(&self) -> Vec<String> {
        vec![
            "id=1".to_string(),
            "id=1'".to_string(),
            "id=1\"".to_string(),
            "id=1 AND 1=1".to_string(),
            "id=1 AND 1=2".to_string(),
            "page=1".to_string(),
            "user=admin".to_string(),
            "search=test".to_string(),
            "q=test".to_string(),
            "query=test".to_string(),
            "redirect=/".to_string(),
            "return_url=/".to_string(),
            "callback=/".to_string(),
            "next=/".to_string(),
            "url=/".to_string(),
            "path=/".to_string(),
            "file=test.txt".to_string(),
            "filename=test.txt".to_string(),
            "name=test".to_string(),
            "action=read".to_string(),
            "cmd=ls".to_string(),
            "command=ls".to_string(),
            "exec=whoami".to_string(),
            "module=index".to_string(),
            "view=index".to_string(),
            "template=index".to_string(),
            "lang=en".to_string(),
            "locale=en".to_string(),
            "debug=1".to_string(),
            "test=1".to_string(),
            "dev=1".to_string(),
            "mode=debug".to_string(),
            "format=json".to_string(),
            "type=json".to_string(),
            "output=json".to_string(),
            "api_key=test".to_string(),
            "token=test".to_string(),
            "key=test".to_string(),
            "auth=test".to_string(),
            "password=test".to_string(),
            "pass=test".to_string(),
            "pwd=test".to_string(),
            "email=test@test.com".to_string(),
            "username=admin".to_string(),
            "login=admin".to_string(),
            "include=/etc/passwd".to_string(),
            "file=/etc/passwd".to_string(),
            "path=/etc/passwd".to_string(),
            "document=/etc/passwd".to_string(),
            "page=../../../../etc/passwd".to_string(),
            "dir=../".to_string(),
            "folder=../".to_string(),
            "download=test.pdf".to_string(),
            "upload=test.pdf".to_string(),
            "import=/".to_string(),
            "load=/".to_string(),
            "read=/".to_string(),
            "fetch=/".to_string(),
            "proxy=http://127.0.0.1".to_string(),
            "host=127.0.0.1".to_string(),
            "ip=127.0.0.1".to_string(),
            "domain=localhost".to_string(),
            "server=localhost".to_string(),
            "port=3306".to_string(),
            "timeout=5000".to_string(),
            "wait=5000".to_string(),
            "sleep=5".to_string(),
            "delay=5".to_string(),
            "version=1.0".to_string(),
            "v=1.0".to_string(),
            "limit=10".to_string(),
            "offset=0".to_string(),
            "start=0".to_string(),
            "end=10".to_string(),
            "size=10".to_string(),
            "count=10".to_string(),
            "max=100".to_string(),
            "min=1".to_string(),
            "sort=asc".to_string(),
            "order=asc".to_string(),
            "by=id".to_string(),
            "field=id".to_string(),
            "column=id".to_string(),
            "table=users".to_string(),
            "from=users".to_string(),
            "where=1=1".to_string(),
            "select=*".to_string(),
            "join=users".to_string(),
            "on=1=1".to_string(),
        ]
    }

    pub fn generate_headers(&self) -> Vec<String> {
        vec![
            "X-Forwarded-For: 127.0.0.1".to_string(),
            "X-Real-IP: 127.0.0.1".to_string(),
            "X-Remote-IP: 127.0.0.1".to_string(),
            "X-Remote-Addr: 127.0.0.1".to_string(),
            "X-Originating-IP: 127.0.0.1".to_string(),
            "X-Client-IP: 127.0.0.1".to_string(),
            "X-Host: 127.0.0.1".to_string(),
            "X-Forwarded-Host: localhost".to_string(),
            "X-Forwarded-Server: localhost".to_string(),
            "X-HTTP-Host-Override: localhost".to_string(),
            "Forwarded: for=127.0.0.1".to_string(),
            "Client-IP: 127.0.0.1".to_string(),
            "True-Client-IP: 127.0.0.1".to_string(),
            "CF-Connecting-IP: 127.0.0.1".to_string(),
            "X-Custom-IP-Authorization: 127.0.0.1".to_string(),
            "X-Rewrite-URL: /admin".to_string(),
            "X-Original-URL: /admin".to_string(),
            "X-Override-URL: /admin".to_string(),
            "X-Forwarded-Proto: https".to_string(),
            "X-Forwarded-Port: 443".to_string(),
            "X-Forwarded-Scheme: https".to_string(),
            "X-Scheme: https".to_string(),
            "Front-End-Https: on".to_string(),
            "X-HTTP-Method-Override: PUT".to_string(),
            "X-HTTP-Method: PUT".to_string(),
            "X-Method-Override: PUT".to_string(),
            "_method: PUT".to_string(),
            "Content-Type: application/json".to_string(),
            "Accept: application/json".to_string(),
            "Accept-Language: en-US".to_string(),
            "Accept-Encoding: gzip, deflate".to_string(),
            "Cache-Control: no-cache".to_string(),
            "Pragma: no-cache".to_string(),
            "Referer: https://www.google.com/".to_string(),
            "Origin: https://www.google.com".to_string(),
            "DNT: 1".to_string(),
            "Connection: keep-alive".to_string(),
            "Upgrade-Insecure-Requests: 1".to_string(),
            "Sec-Fetch-Dest: document".to_string(),
            "Sec-Fetch-Mode: navigate".to_string(),
            "Sec-Fetch-Site: cross-site".to_string(),
            "Sec-Fetch-User: ?1".to_string(),
            "TE: trailers".to_string(),
            "Authorization: Bearer test".to_string(),
            "X-API-Key: test".to_string(),
            "X-Auth-Token: test".to_string(),
            "X-CSRF-Token: test".to_string(),
            "X-Request-ID: 12345".to_string(),
            "X-Correlation-ID: 12345".to_string(),
            "X-Session-ID: 12345".to_string(),
            "X-Trace-ID: 12345".to_string(),
            "X-User-Agent: Mozilla/5.0".to_string(),
            "X-Device-ID: test123".to_string(),
            "X-Request-Source: web".to_string(),
            "X-Application-Context: application".to_string(),
            "X-Context-Path: /".to_string(),
            "X-Servlet-Path: /".to_string(),
            "X-Path-Translated: /".to_string(),
            "X-Path-Info: /".to_string(),
            "X-Resource-Path: /".to_string(),
        ]
    }
}

impl Clone for PayloadGenerator {
    fn clone(&self) -> Self {
        Self
    }
}
